version: "3"

networks:
  redis-network:
    name: url-shortener-network

services: 
  redis:
    image: redis:latest
    container_name: redis
    networks: 
      - redis-network
    ports:
        - 6379:6379
    command: [ "redis-server" ]

  python:
    image: url-shortener:latest
    depends_on: 
      - redis
    container_name: python
    networks: 
      - redis-network

  pytest:
    image: url-shortener:latest
    depends_on: 
      - redis
    container_name: unit-tests
    networks: 
      - redis-network
    entrypoint: ["poetry", "run", "pytest"]